name: Upload Artifact Demo

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest # Runner.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create a Report
        run: |
          echo "Build Successfull" > report.txt
          echo "Generated on $(date)" >> report.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-report
          path: report.txt
